
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

    expose:
      - 5432

    healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5

  application:
    build:
      context: .
    entrypoint: /code/entrypoint.sh
    restart: unless-stopped
    command: uvicorn crm_naive.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - application

volumes:
  postgres_data:
  static_volume:
