
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env

    expose:
      - 5432

    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
       interval: 10s
       timeout: 5s
       retries: 5

  application:
    build:
      context: .
    entrypoint: /app/entrypoint.sh
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 crm_naive.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_naive.settings.prod
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - application

volumes:
  postgres_data:
  static_volume:
