
services:
  db:
    image: postgres:latest
    restart: always
    container_name: db_optimized
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./.env

    ports:
      - "5432:5432"

    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
       interval: 10s
       timeout: 5s
       retries: 5

  application:
    build:
      context: .
    container_name: app_optimized
    entrypoint: /app/entrypoint.sh
    restart: unless-stopped
    command: uvicorn crm_optimized.asgi:application --reload --host 0.0.0.0 --port 8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_optimized.settings.prod
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis_optimized
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_optimized
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - application

volumes:
  postgres_data:
  static_volume:
  redis_data:







